spring:
  application:
    name: office-erp

  # Default profile - local development
  datasource:
    url: jdbc:postgresql://localhost:5432/erp_db
    username: erp_user
    password: erp_pass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

  data:
    redis:
      host: localhost
      port: 6379

  mail:
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8080
  servlet:
    context-path: /

# Custom app properties
app:
  jwt:
    secret: ${JWT_SECRET:dGhpcy1pcy1hLXZlcnktc2VjdXJlLWp3dC1zZWNyZXQta2V5LWZvci1vZmZpY2UtZXJwLTI1Ni1iaXRz}
    access-token-expiry: 900000       # 15 minutes in ms
    refresh-token-expiry: 604800000   # 7 days in ms
  cors:
    allowed-origins: http://localhost:4200,http://localhost:80
  minio:
    url: ${MINIO_URL:http://localhost:9000}
    access-key: ${MINIO_ACCESS_KEY:minio_user}
    secret-key: ${MINIO_SECRET_KEY:minio_pass}
    bucket: erp-files
  payment:
    success-url: https://errorless-defectively-miguelina.ngrok-free.dev/api/v1/finance/budgets/success
    fail-url: https://errorless-defectively-miguelina.ngrok-free.dev/api/v1/finance/budgets/fail
    cancel-url: https://errorless-defectively-miguelina.ngrok-free.dev/api/v1/payments/cancel

# Springdoc / Swagger
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha

sslcommerz:
  store:
    id: karoo69f8757001033
    password: karoo69f8757001033@ssl
  url:
    initiate: https://sandbox.sslcommerz.com/gwprocess/v4/api.php
    validation: https://sandbox.sslcommerz.com/validator/api/validationserverphp.php
  is-sandbox: true

